g++:
	g++ -std=c++17 -pedantic -Wall -g -o rotor *.cpp

exe: g++
	cls
	./rotor.exe C 1 BAUNILHA 1 1 entrada saida

exeExemplo1:
	cls
	./rotor.exe C 1 GIROSCOPIO 1 1 entrada saida
	./rotor.exe D 1 GIROSCOPIO 1 1 saida saidaDeCripto

exeExemplo2:
	cls
	./rotor.exe C 1 BAUNILHA 1 1 entrada saida
	./rotor.exe D 1 BAUNILHA 1 1 saida saidaDeCripto

exeExemplo3:
	cls
	./rotor.exe C 2 GIROSCOPIO BAUNILHA 1 1 17 3 entrada saida
	./rotor.exe D 2 GIROSCOPIO BAUNILHA 1 1 17 3 saida saidaDeCripto

exeExemplo4:
	cls
	./rotor.exe C 3 GIROSCOPIO BAUNILHA SOCORRO 1 1 17 3 9 85 entrada saida
	./rotor.exe D 3 GIROSCOPIO BAUNILHA SOCORRO 1 1 17 3 9 85 saida saidaDeCripto

exeExemplo5:
	cls
	./rotor.exe C 4 GIROSCOPIO BAUNILHA SOCORRO amore 1 1 17 3 9 85 23 14 entrada saida
	./rotor.exe D 4 GIROSCOPIO BAUNILHA SOCORRO amore 1 1 17 3 9 85 23 14 saida saidaDeCripto

exeExemplo6:
	cls
	./rotor.exe C 5 GIROSCOPIO BAUNILHA SOCORRO amore LETSGOOOOOOO 1 1 17 3 9 85 23 14 1 1 entrada saida
	./rotor.exe D 5 GIROSCOPIO BAUNILHA SOCORRO amore LETSGOOOOOOO 1 1 17 3 9 85 23 14 1 1 saida saidaDeCripto