exe:
	cls
	python soueu.py T < teo1.in

fab1:
	cls
	python soueu.py F < fab1.in

fab2:
	cls
	python soueu.py F < fab2.in

fab3:
	cls
	python soueu.py F < fab3.in

fab4:
	cls
	python soueu.py F < fab4.in

fab5:
	cls
	python soueu.py F < fab5.in

pat1:
	cls
	python soueu.py P < pat1.in

pat2:
	cls
	python soueu.py P < pat2.in

pat3:
	cls
	python soueu.py P < pat3.in

pat4:
	cls
	python soueu.py P < pat4.in > pat4.out

pat4b:
	cls
	python soueu.py P < pat4b.in

pat5:
	cls
	python soueu.py P < pat5.in

est1:
	cls
	python soueu.py E < est1.in

est2:
	cls
	python soueu.py E < est2.in

teo1:
	cls
	python soueu.py T < teo1.in

teo2:
	cls
	python soueu.py T < teo2.in