exe: 
	cls
	g++ --std=c++11 *.cpp -o main -lglew32 -lfreeglut -lglu32 -lopengl32
	./main

exeLinux:
	clear
	g++ *.cpp -o main -std=c++11 -Wall -lGL -lGLU -lglut -lGLEW -lglfw -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lXinerama -lXcursor
	./main